const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const core=require('../game-core.js');
assert.equal(core.targetProfile('York',1,1,30).high,false);
assert.equal(core.targetProfile('York',1,1,30).moving,false);
assert.equal(core.targetProfile('York',7,8,20).high,true,'Experienced players get new patterns when returning to York');
assert.equal(core.targetProfile('London',1,1,20).high,false,'High poles wait for a capable weapon');
assert.equal(core.targetProfile('London',4,8,20).reward,3);
assert.ok(core.targetProfile('Norwich',4,8,60).moving);
assert.ok(core.targetProfile('Norwich',8,8,50).duration<core.targetProfile('York',1,1,50).duration);
for(const [city,rank,mult]of [['York',1,0],['York',7,2],['Hull',1,2],['Chester',3,3],['Oxford',5,3],['Oxford',6,4]])assert.equal(core.basketMultiplier(city,rank),mult);
const basket={x:150,previousX:140,y:1180,halfWidth:43};
assert.equal(core.basketCatch({x:145,y:1160},{x:155,y:1190},basket,8),true);
assert.equal(core.basketCatch({x:145,y:1190},{x:155,y:1160},basket,8),false,'An ascending head cannot score a basket');
assert.equal(core.basketCatch({x:180,y:1160},{x:190,y:1190},basket,8),false,'Rim grazes do not earn a catch');
assert.equal(core.basketCatch({x:145,y:1190},{x:155,y:1200},basket,8),false,'A head already below the opening does not score');
let gold=0,saves=0,settled=0;const effects=[];
const head={active:true,isHead:true,x:155,y:1190,prevX:145,prevY:1160,displayHeight:16,chopGold:40,body:{enable:true,velocity:{y:100},stop(){},setAllowGravity(){}}};
const context={ChopCore:core,GROUND_Y:1270,bodyGroup:{getChildren:()=>[head]},addGold(scene,n){gold+=n;},SaveManager:{save(){saves++;}},window:{MobileGame:{combo(){}}},settleHead(){settled++;}};
vm.createContext(context);const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
vm.runInContext(html.slice(html.indexOf('function checkBasketCatch('),html.indexOf('function showAimArrow(')),context);
const scene={remainsFloor:1270,basketCarrier:{...basket,active:true,multiplier:3},tweens:{add(config){effects.push(config);}}};
context.checkBasketCatch(scene);context.checkBasketCatch(scene);
assert.equal(gold,80,'A 3× catch adds two times the 40 gold already awarded');assert.equal(saves,1);assert.equal(head.body.enable,false);assert.equal(effects.length,1);
effects[0].onComplete();assert.equal(settled,1,'Caught heads join the retained pile');
assert.equal(core.comboName(2),'A CUT ABOVE!');assert.equal(core.comboName(5),'HEADS WILL ROLL!');assert.equal(core.comboName(3,'targets'),'HAT TRICK!');
console.log('Regional target progression, clean descending basket catches, one-time multiplier payouts and arcade combo names pass.');
