const fs = require('node:fs');
require('./audio-check.cjs');
require('./install-check.cjs');
require('./calendar-check.cjs');
require('./weather-check.cjs');
require('./progression-check.cjs');
require('./suspension-check.cjs');
require('./ring-layout-check.cjs');
require('./ring-cleanup-check.cjs');
require('./bird-check.cjs');
require('./startup-check.cjs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.resolve(__dirname,'..');
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const appManifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
for(const size of [192,512]) {
  const icon=appManifest.icons.find(i=>i.sizes===`${size}x${size}`);
  assert.ok(icon,`Missing ${size}px app icon`);
  const png=fs.readFileSync(path.join(root,icon.src));
  assert.equal(png.readUInt32BE(16),size);assert.equal(png.readUInt32BE(20),size);
}
assert.ok(appManifest.icons.some(i=>i.purpose.includes('maskable')));
const appleIcon=fs.readFileSync(path.join(root,'assets/app-icon-180.png'));
assert.equal(appleIcon.readUInt32BE(16),180);assert.equal(appleIcon.readUInt32BE(20),180);
console.log('Home-screen manifest references correctly sized standard, maskable and Apple icons.');
for(const [name,count] of [['heads',16],['bodies',4],['jesters',4],['weapons',30]]) {
  const atlas=JSON.parse(fs.readFileSync(path.join(root,`assets/cast-${name}-v2.json`),'utf8'));
  const png=fs.readFileSync(path.join(root,`assets/cast-${name}-v2.png`));
  assert.equal(Object.keys(atlas.frames).length,count);
  for(const {frame} of Object.values(atlas.frames)) {
    assert.ok(frame.x>=0&&frame.y>=0&&frame.w>0&&frame.h>0);
    assert.ok(frame.x+frame.w<=png.readUInt32BE(16)&&frame.y+frame.h<=png.readUInt32BE(20));
  }
}
console.log('Illustrated cast atlases contain 16 faces, four costumes, four jesters and 30 weapons inside their image bounds.');
for (const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) new vm.Script(match[1]);
for (const filename of ['mobile.js','cast-art.js','audio.js','dayNightCycle.js','game-core.js','campaign.js','offline.js','sw.js']) new vm.Script(fs.readFileSync(path.join(root,filename),'utf8'));
const {advanceMeter} = require('../game-core.js');
const {launchVelocity,launchPreview}=require('../game-core.js');
assert.deepEqual(launchVelocity(0,2,1.5,{x:30,y:-10}),{x:30,y:-760});
assert.ok(Math.abs(launchVelocity(-90,1).x+250)<1e-8);
const leftArc=launchPreview(-30,2),rightArc=launchPreview(30,2);
assert.equal(leftArc.length,8);
leftArc.forEach((p,i)=>{assert.ok(Math.abs(p.x+rightArc[i].x)<1e-8);assert.ok(Math.abs(p.y-rightArc[i].y)<1e-8);});
assert.ok(launchPreview(0,2,1.5).at(-1).y < launchPreview(0,2).at(-1).y,'Upgrades lengthen the preview');
assert.ok(launchPreview(0,.5,1,{x:0,y:0},true).at(-1).y > launchPreview(0,.5).at(-1).y,'Rain increases the falling portion');
assert.ok(launchPreview(0,1,1,{x:100,y:0}).at(-1).x > 0,'Wind affects the guide');
console.log('Launch guide matches shared launch velocity, reflects aim, upgrades and wind, and applies rain while falling.');
function simulate(fps,seconds) { let state={position:250,direction:1};for(let i=0;i<fps*seconds;i++) state=advanceMeter(state.position,state.direction,435,1/fps);return state; }
for (const fps of [30,60,90,120,144]) {
  const a=simulate(fps,10), b=simulate(60,10);
  assert.ok(Math.abs(a.position-b.position)<1e-6,`Timing varies at ${fps} fps`);
  assert.equal(a.direction,b.direction);
}
assert.deepEqual(advanceMeter(540,1,300,.1),{position:530,direction:-1});
assert.deepEqual(advanceMeter(260,-1,300,.1),{position:270,direction:1});
const stalled=advanceMeter(250,1,500,7);
assert.ok(stalled.position>=250 && stalled.position<=550);
console.log('Scripts parse; timing matches at 30/60/90/120/144 Hz; overshoot reflection passes.');
const managerSource = html.slice(html.indexOf('const SaveManager = {'),html.indexOf('const baseSizes'));
const marketCatalog=vm.runInNewContext(html.slice(html.indexOf('const marketItems = ['),html.indexOf('// Places the player can visit'))+'\nmarketItems');
const context = {SAVE_VERSION:2,clearTimeout,marketItems:marketCatalog};
vm.createContext(context);
vm.runInContext(managerSource+'\nthis.manager = SaveManager; this.validateSave = data => SaveManager.validate(data);',context);
const valid = {gold:10,fame:0,xp:1,level:1,itemsOwned:{Turnips:1},citiesUnlocked:['York'],upgradesOwned:{storageLevel:1,weaponLevel:1}};
assert.equal(context.validateSave(valid),true);
for (const bad of [null,{}, {...valid,level:Infinity},{...valid,level:1e9},{...valid,gold:NaN},{...valid,itemsOwned:null},{...valid,itemsOwned:{Turnips:-1}},{...valid,upgradesOwned:{storageLevel:17,weaponLevel:1}}]) assert.equal(context.validateSave(bad),false);
console.log('Legacy save accepted; null, corrupt, out-of-range and non-finite saves rejected.');
assert.equal(context.validateSave({...valid,itemsOwned:{Turnips:6,Potatoes:5}}),false,'Combined inventory cannot exceed cart capacity');
assert.equal(context.validateSave({...valid,itemsOwned:{UnknownCargo:1}}),false,'Unknown goods cannot occupy unusable cart space');
assert.equal(context.validateSave({...valid,itemsOwned:{Turnips:5,Potatoes:5}}),true);
assert.equal(context.validateSave({...valid,itemsOwned:{Turnips:160},upgradesOwned:{storageLevel:16,weaponLevel:1}}),true);
Object.assign(context, {player:{},cities:[{name:'York'}],gameUpgrades:[{mult:1.1},{mult:1.2},{mult:1.3}],currentDay:1,currentMonth:0,currentCity:'York',months:Array(12),marketItems:marketCatalog,dateText:null,Phaser:{Math:{Clamp:(n,min,max)=>Math.min(max,Math.max(min,n))}},Campaign:{restore(){},visit(){}}});
context.manager.apply({...valid,upgradesOwned:{...valid.upgradesOwned,purchasedUpgrades:[true,false,true]}});
assert.equal(context.fameMultiplier,1.3,'Restoring purchased boosts restores their strongest effect');
assert.equal(context.player.maxStorage,10);
context.manager.apply(valid);
assert.equal(context.fameMultiplier,1,'A legacy save without purchases resets any old bonus');
const upgradeSource=html.slice(html.indexOf('function buyUpgrade('),html.indexOf('// Buying from the trading market'));
const upgrades={player:{gold:1000},fame:10,fameMultiplier:1,gameUpgrades:[{cost:150,fameReq:0,mult:1.1},{cost:300,fameReq:3,mult:1.2},{cost:600,fameReq:6,mult:1.3}],goldText:{setText(){}},formatGold:String,SaveManager:{save(){}}};
vm.createContext(upgrades);vm.runInContext(upgradeSource,upgrades);
assert.equal(upgrades.buyUpgrade({},2),true);assert.equal(upgrades.player.gold,400);assert.equal(upgrades.fameMultiplier,1.3);
assert.equal(upgrades.buyUpgrade({},2),false,'Cannot pay for the same boost twice');
assert.equal(upgrades.buyUpgrade({},0),false,'A weaker boost cannot waste gold or reduce the bonus');
assert.equal(upgrades.player.gold,400);assert.equal(upgrades.buyUpgrade({},99),false);
upgrades.fameMultiplier=1;upgrades.fame=0;assert.equal(upgrades.buyUpgrade({},1),false,'Fame requirement enforced');
upgrades.player.gold=0;assert.equal(upgrades.buyUpgrade({},0),false,'Gold requirement enforced');
console.log('Fame upgrades restore, reset for legacy saves, charge once and reject weaker or unaffordable purchases.');
const store=new Map([['choptoit-save','broken JSON'],['choptoit-save-backup',JSON.stringify(valid)]]);
context.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};
let recovered;
context.manager.apply=d=>{recovered=d;};context.manager.load();
assert.equal(recovered.gold,10);assert.equal(context.manager.recovered,true);
context.manager.getData=()=>({...valid,gold:25});context.manager.performSave();
assert.equal(JSON.parse(store.get('choptoit-save')).gold,25);
context.manager.clear();assert.equal(store.size,0);
console.log('Corrupt primary save recovers from backup; new save writes; clear removes both copies.');
store.set('choptoit-save','unreadable primary');store.set('choptoit-save-backup','unreadable backup');
context.manager.load();
assert.equal(context.manager.unreadable,true);assert.equal(context.manager.disabled,true);
context.manager.performSave();
assert.equal(store.get('choptoit-save'),'unreadable primary');
assert.equal(store.get('choptoit-save-backup'),'unreadable backup');
assert.equal(context.validateSave({...valid,saveVersion:3}),false,'Future saves must not be silently downgraded');
store.set('choptoit-save-backup',JSON.stringify(valid));
context.manager.restore({...valid,gold:55,saveVersion:2});
assert.equal(JSON.parse(store.get('choptoit-save')).gold,55);
assert.equal(JSON.parse(store.get('choptoit-save-backup')).gold,10,'Import must not replace a valid backup with a broken primary');
assert.throws(()=>context.manager.restore({gold:'bad'}));
for(const itemsOwned of [{Turnips:11},{UnknownCargo:1}]) {
  const untouched=store.get('choptoit-save');
  assert.throws(()=>context.manager.restore({...valid,itemsOwned}));
  assert.equal(store.get('choptoit-save'),untouched,'Invalid cargo must not replace existing progress');
}
assert.equal(JSON.parse(store.get('choptoit-save')).gold,55);
assert.equal(context.manager.clear(),true,'Explicit fresh start works when automatic saving is disabled');
assert.equal(store.size,0);
console.log('Unreadable saves stay intact; future versions reject; restore preserves valid recovery copy; explicit reset works.');
store.set('choptoit-save',JSON.stringify(valid));
function savedTab(gold) {
  const tab={SAVE_VERSION:2,clearTimeout,localStorage:context.localStorage,marketItems:marketCatalog};
  vm.createContext(tab);vm.runInContext(managerSource+'\nthis.manager=SaveManager;',tab);
  tab.manager.apply=()=>{};tab.manager.getData=()=>({...valid,gold});tab.manager.load();
  return tab.manager;
}
const firstTab=savedTab(25), staleTab=savedTab(99);
firstTab.performSave();staleTab.performSave();
assert.equal(staleTab.conflict,true);assert.equal(staleTab.disabled,true);
assert.equal(JSON.parse(store.get('choptoit-save')).gold,25,'Stale copy must not overwrite latest progress');
assert.equal(JSON.parse(store.get('choptoit-save-backup')).gold,10,'Stale copy must not rotate recovery backup');
const reopenedTab=savedTab(30);reopenedTab.performSave();
assert.equal(reopenedTab.conflict,false);assert.equal(JSON.parse(store.get('choptoit-save')).gold,30);
assert.equal(firstTab.checkCurrent(),false,'Storage notification identifies an outdated copy');
const beforeReset=savedTab(40);store.delete('choptoit-save');beforeReset.performSave();
assert.equal(beforeReset.conflict,true);assert.equal(store.has('choptoit-save'),false,'Old copy must not undo a new-story reset');
console.log('Stale tabs preserve newer saves and backups; reload resumes writing; deleted saves cannot be resurrected.');
const pricingSource=html.slice(html.indexOf('function refreshMarketPrices()'),html.indexOf('function chooseTargetType()'));
const pricing={cities:[{name:'York',region:'North',modifiers:{Potatoes:{buy:.5,sell:2}}}],currentCity:'York',marketItems:[{name:'Potatoes',buy:2,sell:2},{name:'Imported silk',buy:30,sell:50,regions:['South']}],dailyBuySpecial:'Potatoes',dailySellSpecial:null,Phaser:{Math:{FloatBetween:()=>1.25,Between:()=>0}}};
pricing.ChopCore=require('../game-core.js');
vm.createContext(pricing);vm.runInContext(pricingSource+'\nrefreshMarketPrices();',pricing);
for(const item of pricing.marketItems) assert.ok(item.currentSell<=item.currentBuy,'Same-town buy/sell loop must not print money');
assert.equal(pricing.marketItems[0].currentBuy,2);
assert.equal(pricing.marketItems[0].currentSell,2);
assert.equal(pricing.marketItems[1].stock,0,'Imported goods cannot be bought outside their region');
const {marketQuote,tradeProfiles}=pricing.ChopCore;
for (const [exported] of Object.values(tradeProfiles)) assert.ok(Object.values(tradeProfiles).some(([,demand])=>demand===exported),`${exported} needs a destination buyer`);
for(const city of Object.keys(tradeProfiles)) for(const base of [1,2,5,9,20,400]) for(const name of [...tradeProfiles[city],'ordinary']) for(const shift of [.9,1,1.1]) for(const special of [[false,false],[true,false],[false,true],[true,true]]) {
  const q=marketQuote(city,{name,buy:base},shift,...special);
  assert.ok(Number.isSafeInteger(q.buy)&&Number.isSafeInteger(q.sell)&&q.sell>0&&q.sell<=q.buy);
}
for(const [from,to,name,base] of [['York','Durham','Wool',9],['Durham','Chester','Salt',8],['Chester','London','Mead',5]]) {
  const cost=marketQuote(from,{name,buy:base},1.1).buy;
  const revenue=marketQuote(to,{name,buy:base},.9,true).sell;
  assert.ok(revenue>cost,`${name} export route must remain profitable across daily variation`);
}
console.log('Town exports have profitable early routes; all price bands and specials prevent same-town arbitrage.');
const {affordableQuantity}=pricing.ChopCore;
assert.equal(affordableQuantity(11,3,20,10),3);
assert.equal(affordableQuantity(100,3,2,10),2);
assert.equal(affordableQuantity(100,3,20,1),1);
assert.equal(affordableQuantity(100,0,20,10),0);
assert.equal(affordableQuantity(100,3,20,-1),0);
const transactions={marketItems:[{name:'Wool',currentBuy:5,currentSell:4,stock:8,fameReq:2}],inventory:{},player:{gold:100,maxStorage:10},fame:2,updateMarketUI(){},showMarketQuote(){},sellingQuotes:[],buyingQuotes:[],goldText:{setText(){}},formatGold:String,SaveManager:{save(){}},Campaign:{state:{sold:0}}};
transactions.getInventoryCount=()=>Object.values(transactions.inventory).reduce((a,b)=>a+b,0);
transactions.addGold=(_scene,amount)=>{transactions.player.gold+=amount;};
vm.createContext(transactions);vm.runInContext(html.slice(html.indexOf('function buyMarketItem('),html.indexOf('// Update market text lines')),transactions);
assert.equal(transactions.buyMarketItem({},0,8),8);assert.equal(transactions.player.gold,60);assert.equal(transactions.inventory.Wool,8);assert.equal(transactions.marketItems[0].stock,0);
assert.equal(transactions.buyMarketItem({},0,1),0);
assert.equal(transactions.sellMarketItem({},0,8),8);assert.equal(transactions.player.gold,92);assert.equal(transactions.inventory.Wool,0);assert.equal(transactions.marketItems[0].stock,8);assert.equal(transactions.Campaign.state.sold,8);
for(const qty of [-1,0,1.5,Infinity]) { assert.equal(transactions.buyMarketItem({},0,qty),0);assert.equal(transactions.sellMarketItem({},0,qty),0); }
assert.equal(transactions.sellMarketItem({},0,1),0);assert.equal(transactions.Campaign.state.sold,8);
transactions.player.maxStorage=1;assert.equal(transactions.buyMarketItem({},0,2),0);
transactions.player.gold=0;assert.equal(transactions.buyMarketItem({},0,1),0);
console.log('Batch trade quantities respect purse, stock and capacity; sales update exact contract counts and reject invalid amounts.');
console.log('Discounts, regional modifiers and imported goods cannot create same-town money loops.');
const fameSource=html.slice(html.indexOf('function gainFame('),html.indexOf('function showGoldGain('));
let awardedXP=0, feedbackText='', popupText='';
const fameContext={fame:1,fameMultiplier:2,fameText:{setText(){}},formatGold:String,addXP:(_scene,n)=>{awardedXP+=n;},SaveManager:{save(){}},window:{MobileGame:{feedback:message=>{feedbackText=message;}}}};
vm.createContext(fameContext);vm.runInContext(fameSource,fameContext);
const fameScene={time:{delayedCall(){}},tweens:{add(){}},add:{text:(_x,_y,text)=>{popupText=text;return {y:0,setOrigin(){return this;}};}}};
fameContext.gainFame(fameScene,{x:0,y:0,targetType:'holyMonk'},-2);
assert.equal(fameContext.fame,0);assert.equal(awardedXP,0);assert.match(feedbackText,/Avoid the monks/);assert.equal(popupText,'-1 fame');
assert.equal(context.validateSave({...valid,fame:fameContext.fame}),true,'Penalty must leave a saveable state');
fameContext.gainFame(fameScene,{x:0,y:0,targetType:'royal'},3);
assert.equal(fameContext.fame,6);assert.equal(awardedXP,15);assert.equal(popupText,'+6 fame');
assert.match(feedbackText,/Royal target · \+6 fame/);
fameContext.gainFame(fameScene,{x:0,y:0,targetType:'holyMonk'},-2);
assert.equal(fameContext.fame,4,'Purchased fame boosts must not amplify penalties');
console.log('Fame penalties clamp at zero without negative XP; rewards and hit messages include the actual multiplier.');
const {create,chapters}=require('../campaign.js');
const campaign=create();
const tracker=create();
const startingStats={chops:0,weapon:1,rank:1,fame:0};
assert.match(tracker.nextObjective(startingStats).text,/Land 3 successful chops · 0\/3/);
assert.equal(tracker.nextObjective({...startingStats,chops:3}).ready,true);
tracker.claim({...startingStats,chops:3});
assert.match(tracker.nextObjective({...startingStats,chops:3}).text,/Upgrade your weapon/);
assert.match(tracker.nextObjective({...startingStats,weapon:2}).text,/Hit 5 flying targets/);
tracker.restore({claimed:5,targets:60});
assert.equal(tracker.nextObjective({...startingStats,chops:49,fame:15}).ready,false);
assert.match(tracker.nextObjective({...startingStats,chops:49,fame:15}).text,/Land 50 successful chops · 49\/50/);
assert.equal(tracker.nextObjective({...startingStats,chops:50,fame:15}).ready,true);
tracker.restore({claimed:6});
assert.equal(tracker.nextObjective(startingStats,1000000).ready,false);
assert.equal(tracker.nextObjective(startingStats,1000001).ready,true);
tracker.advance(360);
assert.equal(tracker.nextObjective(startingStats,1000001).ready,false);
assert.match(tracker.nextObjective(startingStats).caption,/FREE PLAY/);
console.log('Contract tracker covers preparation, reward claims, final funding and post-deadline free play.');
assert.equal(campaign.claim({chops:0}),null);
const hero={chops:100,weapon:8,rank:5,fame:15};
campaign.state.targets=60;campaign.state.sold=10;campaign.visit('Durham');campaign.visit('Chester');campaign.visit('London');
let reward=0;
for(const chapter of chapters) { const claimed=campaign.claim(hero);assert.equal(claimed.title,chapter.title);reward+=claimed.reward; }
assert.ok(reward>1000001,'Campaign contracts cannot fund the stated goal');
assert.equal(campaign.claim(hero),null,'Final contract must not be paid twice');
assert.equal(campaign.finish('freedom',1000000),false);
assert.equal(campaign.finish('freedom',1000001),true);
assert.equal(campaign.finish('reform',1000001),false,'Ending must be one-time');
const restored=create();restored.restore(JSON.parse(JSON.stringify(campaign.state)));
assert.deepEqual(restored.state,campaign.state);
const deadline=create();deadline.advance(359);assert.equal(deadline.state.ending,null);deadline.advance(1);assert.equal(deadline.state.ending,'expired');
assert.equal(deadline.claim(hero),null);
const overdue=create();overdue.restore({days:360,ending:null,epilogueSeen:true});
assert.equal(overdue.state.ending,'expired');assert.equal(overdue.state.epilogueSeen,false);
const completed=create();completed.restore({days:400,ending:'freedom',epilogueSeen:true});
assert.equal(completed.state.ending,'freedom','Free play after a successful ending must retain that ending');
console.log('Six contracts, one-time payouts, funded goal, ending choice, campaign save roundtrip and 360-day deadline pass.');
