const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
let notices=[],saves=0,updates=0;
const context={xp:0,level:1,xpThreshold:10,onLevelUp(){notices.push(context.level);},updateXPUI(){updates++;},SaveManager:{save(){saves++;}}};
vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('function addXP('),html.indexOf('function updateXPUI(')),context);
context.addXP({},39);
assert.equal(context.level,3);
assert.equal(context.xp,16);
assert.equal(context.xpThreshold,17);
assert.deepEqual(notices,[3],'One reward announces the final earned rank once');
context.addXP({},1);
assert.equal(context.level,4);
assert.equal(context.xp,0);
assert.equal(context.xpThreshold,22);
assert.deepEqual(notices,[3,4]);
for(const amount of [0,-1,NaN,Infinity,undefined]) context.addXP({},amount);
assert.equal(context.xp,0);assert.equal(context.level,4);
assert.equal(saves,2);assert.equal(updates,2);
// Equivalent accumulated rewards must earn the same rank and remaining XP.
Object.assign(context,{xp:0,level:1,xpThreshold:10});
for(let i=0;i<40;i++) context.addXP({},1);
assert.equal(context.level,4);assert.equal(context.xp,0);
context.addXP({},Number.MAX_SAFE_INTEGER);
assert.ok(Number.isFinite(context.xp)&&context.xp>=0&&context.xp<context.xpThreshold);
console.log('Large XP rewards grant every earned rank, preserve the remainder, notify once and reject invalid rewards.');
