const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const context={FEATURES:{weather:true},currentWeather:'fog'};
vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('function applyTargetWeather('),html.indexOf('function applyRandomWeather(')),context);
class Target extends EventEmitter { setAlpha(alpha){this.alpha=alpha;return this;} }
const active=new Set();
const scene={tweens:{add(config){const tween={config,stop(){active.delete(tween);}};active.add(tween);return tween;}}};
const target=new Target();target.jester=new Target();
context.applyTargetWeather(scene,target);
assert.equal(active.size,0,'Fog crosses the scene without fading the cast');
for(const tween of active) assert.equal(tween.config.alpha,.4);
context.applyTargetWeather(scene,target);
assert.equal(active.size,0,'Fog crosses the scene without fading the cast');
assert.equal(target.listenerCount('destroy'),1);
context.currentWeather='clear';
context.applyTargetWeather(scene,target);
assert.equal(active.size,0);
assert.equal(target.alpha,1);assert.equal(target.jester.alpha,1);
context.currentWeather='fog';
context.applyTargetWeather(scene,target);
target.emit('destroy');target.jester.emit('destroy');
assert.equal(active.size,0,'Destroyed cast must release its looping weather effects');
const solo=new Target();
context.applyTargetWeather(scene,solo);
assert.equal(active.size,0,'Fog does not pulse solo targets');
context.FEATURES.weather=false;
context.applyTargetWeather(scene,solo);
assert.equal(active.size,0);
console.log('Scene fog leaves cast opacity stable, restores old faded targets and releases obsolete fog tweens.');
