const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const context={FEATURES:{weather:true},currentWeather:'fog'};
vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('function applyTargetWeather('),html.indexOf('function applyRandomWeather(')),context);
class Target extends EventEmitter { setAlpha(alpha){this.alpha=alpha;return this;} }
const active=new Set();
const scene={tweens:{add(config){const tween={config,stop(){active.delete(tween);}};active.add(tween);return tween;}}};
const target=new Target();target.jester=new Target();
context.applyTargetWeather(scene,target);
assert.equal(active.size,0,'Fog crosses the scene without fading the cast');
for(const tween of active) assert.equal(tween.config.alpha,.4);
context.applyTargetWeather(scene,target);
assert.equal(active.size,0,'Fog crosses the scene without fading the cast');
assert.equal(target.listenerCount('destroy'),1);
context.currentWeather='clear';
context.applyTargetWeather(scene,target);
assert.equal(active.size,0);
assert.equal(target.alpha,1);assert.equal(target.jester.alpha,1);
context.currentWeather='fog';
context.applyTargetWeather(scene,target);
target.emit('destroy');target.jester.emit('destroy');
assert.equal(active.size,0,'Destroyed cast must release its looping weather effects');
const solo=new Target();
context.applyTargetWeather(scene,solo);
assert.equal(active.size,0,'Fog does not pulse solo targets');
context.FEATURES.weather=false;
context.applyTargetWeather(scene,solo);
assert.equal(active.size,0);
console.log('Scene fog leaves cast opacity stable, restores old faded targets and releases obsolete fog tweens.');
let fogConfig;
const fogScene={add:{particles(){return {setDepth(depth){assert.ok(depth>20,'Mist must cover targets rather than fade their sprites');return this;},createEmitter(config){fogConfig=config;return {};}};}}};
Object.assign(context,{GAME_WIDTH:800,FOG_MIN_Y:140,FOG_MAX_Y:1540,scene:fogScene});
vm.runInContext(html.slice(html.indexOf("  fogParts = scene.add.particles('mist-soft')"),html.indexOf('  const windG =')),context);
assert.ok(fogConfig.alpha.start*.96>.8,'A fresh dense bank strongly obscures a target at its centre');
assert.ok(256*fogConfig.scale.start>600,'Banks span most of the playfield');
assert.ok(fogConfig.x+128*fogConfig.scale.start < -327,'New banks begin completely outside even the widest camera view');
assert.ok(fogConfig.y.min<-1200&&fogConfig.y.max>1100,'Fog reaches both high and low targets');
assert.equal(fogConfig.alpha.end,0,'Each bank dissipates rather than remaining opaque');
assert.ok(fogConfig.frequency<=500&&fogConfig.maxParticles<=40,'Dense fog has a bounded mobile particle budget');
let emitted=0,started=0;
Object.assign(context,{FEATURES:{weather:true},Math:{random:()=>.9},currentMonth:5,Phaser:{Utils:{Array:{GetRandom:()=> 'fog'}}},windForce:{},weatherText:{setText(){}},weatherIndicator:{setText(){}},rainEmitter:null,snowEmitter:null,windEmitter:null,targetGroup:{getChildren:()=>[]},fogEmitter:{stop(){},start(){started++;},emitParticle(n){emitted+=n;}}});
vm.runInContext(html.slice(html.indexOf('function applyRandomWeather('),html.indexOf('function arrowForWind(')),context);
context.applyRandomWeather({time:{now:0}});assert.equal(started,1);assert.equal(emitted,10,'Initial fog banks enter from the edge; none spawn inside the view');
context.applyRandomWeather({time:{now:100},trickClearFogUntil:8000});assert.equal(started,1,'Incense stops fog from returning during its eight-second bonus');
console.log('Thicker foreground fog wafts from the side across high and low targets, drifts and dissipates with a capped particle budget.');
